project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Energy Consumption Analysis"
  author:
    - Jeremy Qu (jq2406)
    - Matt Xi (yx2933)
  repo-url: https://github.com/JiamingQu1/US-Energy-Consumption-Analysis.git
  date: 11/20/2024
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


